### ISSUE TITLE
[BUG] Plugin install fails with error: "karuppiah7890/helm-schema-gen crit platform windows/amd64 is not supported"

### ISSUE THREAD

**Issue by dmusicant-dk** [karuppiah7890/helm-schema-gen#5]
When I attempt to install the plugin (using GitBash) it fails and says it doesn't work on Windows.

**Command Run:** 
`helm plugin install https://github.com/karuppiah7890/helm-schema-gen`

**Error:**
```plaintext
karuppiah7890/helm-schema-gen crit platform windows/amd64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/karuppiah7890/helm-schema-gen/issues/new
Error: plugin install hook for "schema-gen" exited with error
```

**Comment by karuppiah7890** [comment]
Oops. Let me check this out

**Comment by karuppiah7890** [comment]
Actually, I just realized that the releases page does not have any binary for windows, even though I have mentioned it in goreleaser spec

**Comment by karuppiah7890** [comment]
Also, the install script also errors out for windows

**Comment by dmusicant-dk** [comment]
> Also, the install script also errors out for windows

Sorry, I'm confused. Isn't that what my bug is about? or did you mean install script for something this plugin uses?

**Comment by karuppiah7890** [comment]
Yes, that's what the error is about. It's more like a clear simple error rather than any hard to debug thing 😅 It's the install script of this plugin only.

I just found out that goreleaser does not build for windows by default. At least that's what the latest doc says. I'm going to make the change for releasing for windows too and then release a new version. I should have checked the releases page

**Comment by karuppiah7890** [comment]
@dmusicant-dk Could you please try again? I have released a newer version for the plugin

**Comment by dmusicant-dk** [comment]
When I run `helm plugin install https://github.com/karuppiah7890/helm-schema-gen --debug` I now get the error:

```plaintext
[debug] vcs_installer.go:162: updating https://github.com/karuppiah7890/helm-schema-gen
Error: Unable to update repository: exit status 1
helm.go:81: [debug] Unable to update repository: exit status 1
```

**Comment by dmusicant-dk** [comment]
Ok, I figured out the issue. Your README says to use `helm plugin install https://github.com/karuppiah7890/helm-schema-gen` but that fails. When I instead use `helm plugin install https://github.com/karuppiah7890/helm-schema-gen.git` it installs without error (notice the ".git").

And now it works! Thank you

**Comment by karuppiah7890** [comment]
Ah. Interesting, I'll check it out and then close the issue

**Comment by karuppiah7890** [comment]
Created another issue for the README instruction :) Thanks for reporting it!
