### ISSUE TITLE
helm-docs

### ISSUE THREAD

**Issue by estahn** [karuppiah7890/helm-schema-gen#8]
@karuppiah7890 How would you feel adding this functionality to `helm-docs` instead?

https://github.com/norwoodj/helm-docs/issues/74

**Comment by karuppiah7890** [comment]
I'll look into, but I can't commit anything. 😅 And thanks for communicating about this! :)

**Comment by karuppiah7890** [comment]
And I would still keep this standalone tool just like that. I'll check how this feature can be added to helm-docs. I'm guessing there's a bit more work, as the current code generates just types and nothing else. In helm-docs, we want description, and I'm assuming probably even things like, if a field is required or not? Especially if there's no default value for it (a rare case though) in the default values.yaml . Another thing is, the current code also doesn't add any extra schema like additionalProperties to mention if unknown properties are allowed or not. Currently it's allowed, as that's the default. 

This tool currently just gives the user a head start on writing their schema but not exactly a complete solution. But yeah, I agree that helm-docs capability can help the schema to be more enriched. I haven't found the time and reason to use helm-docs yet, as I don't use helm much now. But I'll check it out and get back into this
